### ISSUE TITLE
Создать github workflow для билда и деплоя бекенда

### ISSUE THREAD

**Issue by prafdin** [IT-Prospects/business-calendar-backend#30]
Необходимо создать github actions workflow, при помощи которого можно было бы поднимать бекенд в контейнере. Кроме того, после билда в бакете должен создаваться скрипт для миграции в бд

**Comment by Jendozzz** [comment]
Создан [workflow](https://github.com/IT-Prospects/business-calendar-backend/blob/main/.github/workflows/deploy%20with%20docker.yml) в репозитории бэкенда
Добавлены необходимые переменные и секреты в репозиторий
Написана [документация](https://github.com/IT-Prospects/business-calendar-configuration/blob/GHA-deploy-backend-with-docker/docs/GHActions%20deploy%20backend%20app%20with%20Docker.md) 
[PR](https://github.com/IT-Prospects/business-calendar-configuration/pull/27)

**Comment by prafdin** [comment]
```
У тебя при сборке имеджа заполняется или Production либо Development setting.json, но само приложение запускается без какого-то флага (prod or dev) https://github.com/IT-Prospects/business-calendar-backend/blob/main/Dockerfile#L11
насколько я помню, если ничего не указывать, то он будет брать настройки из Production файлика
```
